import { Agent } from './types';

export const GITHUB_PORTFOLIO_URL = "https://github.com/bryanengel72/agentportfolio";

export const AGENTS: Agent[] = [
  {
    id: 'tax-savvy',
    title: 'TaxSavvy Advisor',
    description: 'Analyzes your financial situation to uncover potential tax deductions and savings opportunities based on current US tax regulations.',
    category: 'Finance',
    imageUrl: 'https://picsum.photos/seed/tax-savvy/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/taxsavvy-advisor-8666a526/remix',
    tags: ['Finance', 'Tax', 'Advice'],
    match: 98,
    rating: 'ADVANCED',
    duration: 'On-Demand'
  },
  {
    id: 'trend-blogger',
    title: 'TrendBlogger',
    description: 'Creates engaging 1000-word blog posts optimized for search engines using real-time Google Trends data and proven SEO strategies.',
    category: 'Marketing',
    imageUrl: 'https://picsum.photos/seed/trend-blogger/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/trends-to-blog-702e6b1c/remix',
    tags: ['SEO', 'Blogging', 'Trends'],
    match: 95,
    rating: 'INTERMEDIATE',
    duration: 'Fast'
  },
  {
    id: 'career-sitrep',
    title: 'Career SITREP',
    description: 'Converts military occupation codes and experiences into comprehensive, professional civilian job profiles with precision and respect.',
    category: 'Career',
    imageUrl: 'https://picsum.photos/seed/career-sitrep/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/career-sitrep-eebc6534/remix',
    tags: ['Military', 'Resume', 'Transition'],
    match: 99,
    rating: 'EASY',
    duration: 'On-Demand'
  },
  {
    id: 'ai-roadmap',
    title: 'AI Roadmap Generator',
    description: 'Create comprehensive, executive-level AI technology roadmaps tailored to your business goals and industry context.',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/ai-roadmap/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/ai-roadmap-generator-3666eebf/remix',
    tags: ['Strategy', 'Planning', 'Executive'],
    match: 92,
    rating: 'ADVANCED',
    duration: 'Strategic'
  },
  {
    id: 'certpath-ai',
    title: 'CertPath AI',
    description: 'Discover the perfect professional certifications for your career path with personalized, data-driven recommendations.',
    category: 'Career',
    imageUrl: 'https://picsum.photos/seed/certpath-ai/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/certpath-ai-ba236b0d/remix',
    tags: ['Education', 'Growth', 'Career'],
    match: 88,
    rating: 'EASY',
    duration: 'On-Demand'
  },
  {
    id: 'vendor-vibes',
    title: 'VendorVibes',
    description: 'Evaluate vendors and suppliers with comprehensive analysis of their online presence, reviews, and market reputation.',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/vendor-vibes/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/vendorvibes-8609c2c3/remix',
    tags: ['Procurement', 'Analysis', 'Vetting'],
    match: 90,
    rating: 'INTERMEDIATE',
    duration: 'Real-time'
  },
  {
    id: 'plant-id',
    title: 'PlantID Expert',
    description: 'Transform plant photos into detailed botanical insights with instant species identification and fascinating scientific details.',
    category: 'Lifestyle',
    imageUrl: 'https://picsum.photos/seed/plant-id/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/plantid-expert-53d8042e/remix',
    tags: ['Nature', 'Identification', 'Botany'],
    match: 97,
    rating: 'EASY',
    duration: 'Instant'
  },
  {
    id: 'market-timeline',
    title: 'Market Event Timeline',
    description: 'Transform complex market data into stunning visual timelines that reveal the relationships between historical events and financial market movements.',
    category: 'Finance',
    imageUrl: 'https://picsum.photos/seed/market-timeline/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/market-event-timeline-visualizer-ab2555ba/remix',
    tags: ['Stocks', 'History', 'Data Viz'],
    match: 85,
    rating: 'ADVANCED',
    duration: 'Analytical'
  },
  {
    id: 'ad-optimizer',
    title: 'Ad Combination Optimizer',
    description: 'Analyzes and recommends the most effective combinations of ad copy and images for Meta and Google Ads campaigns.',
    category: 'Marketing',
    imageUrl: 'https://picsum.photos/seed/ad-optimizer/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/ad-combination-optimizer-4e4c8dd5/remix',
    tags: ['Ads', 'Optimization', 'Growth'],
    match: 93,
    rating: 'INTERMEDIATE',
    duration: 'Performance'
  },
  {
    id: 'competitor-pulse',
    title: 'CompetitorPulse',
    description: 'Delivers comprehensive weekly intelligence reports analyzing your competitors moves, market trends, and strategic developments.',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/competitor-pulse/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/competitorpulse-6173b518/remix',
    tags: ['Intelligence', 'Strategy', 'Monitoring'],
    match: 96,
    rating: 'ADVANCED',
    duration: 'Weekly'
  },
  {
    id: 'proposal-craftsman',
    title: 'Proposal Craftsman',
    description: 'Generate professional, customized PDF proposals that perfectly align with your client\'s needs, backed by targeted company research.',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/proposal-craftsman/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/proposal-craftsman-b19c947c/remix',
    tags: ['Sales', 'Docs', 'B2B'],
    match: 91,
    rating: 'INTERMEDIATE',
    duration: 'Fast'
  },
  {
    id: 'ccpa-gen',
    title: 'CCPA Compliance Generator',
    description: 'Create comprehensive CCPA-compliant privacy policies and procedures documents tailored for California businesses.',
    category: 'Legal',
    imageUrl: 'https://picsum.photos/seed/ccpa-gen/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/privacy-compliance-letter-creator-ae1dfd6a/remix',
    tags: ['Privacy', 'Compliance', 'California'],
    match: 99,
    rating: 'EXPERT',
    duration: 'Specific'
  },
  {
    id: 'contract-sum',
    title: 'Contract Summarizer',
    description: 'Transform lengthy government contracts into actionable executive summaries highlighting key objectives, stakeholders, and critical terms.',
    category: 'Legal',
    imageUrl: 'https://picsum.photos/seed/contract-sum/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/contract-summarizer-fbf2785c/remix',
    tags: ['Contracts', 'Summarization', 'Government'],
    match: 94,
    rating: 'ADVANCED',
    duration: 'Instant'
  },
  {
    id: 'story-spark',
    title: 'Story Spark',
    description: 'Creates magical, personalized stories that inspire young minds with positive values and endless imagination.',
    category: 'Creative',
    imageUrl: 'https://picsum.photos/seed/story-spark/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/story-spark-generator-6c7170bd/remix',
    tags: ['Kids', 'Writing', 'Fun'],
    match: 89,
    rating: 'EASY',
    duration: 'Infinite'
  },
  {
    id: 'email-insight',
    title: 'Email Insight Optimizer',
    description: 'Transform your inbox management with intelligent email analysis that provides clear priorities, categories, and actionable recommendations.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/email-insight/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/email-insight-optimizer-f5a083f0/remix',
    tags: ['Email', 'Organization', 'Time-saver'],
    match: 92,
    rating: 'EASY',
    duration: 'Daily'
  },
  {
    id: 'brand-voice',
    title: 'Brand Voice Calibrator',
    description: 'Develop comprehensive brand voice guidelines that ensure consistent communication across corporate, team, and customer-facing channels.',
    category: 'Marketing',
    imageUrl: 'https://picsum.photos/seed/brand-voice/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/brand-voice-calibrator-d4d813b3/remix',
    tags: ['Branding', 'Communication', 'Identity'],
    match: 90,
    rating: 'INTERMEDIATE',
    duration: 'One-time'
  },
  {
    id: 'epic-ehr',
    title: 'Epic EHR Test Script',
    description: 'Creates comprehensive, standardized test scripts for Epic EHR systems with detailed steps, prerequisites, and expected outcomes.',
    category: 'Development',
    imageUrl: 'https://picsum.photos/seed/epic-ehr/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/epic-ehr-test-script-generator-667925a8/remix',
    tags: ['Healthcare', 'QA', 'Testing'],
    match: 98,
    rating: 'EXPERT',
    duration: 'Technical'
  },
  {
    id: 'compliance-advisor',
    title: 'Compliance Advisor',
    description: 'Get expert guidance on GDPR, CCPA, and EU AI Act compliance with comprehensive gap analysis, remediation planning, and training.',
    category: 'Legal',
    imageUrl: 'https://picsum.photos/seed/compliance-advisor/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/compliance-advisor-329bd83e/remix',
    tags: ['GDPR', 'Regulations', 'Global'],
    match: 95,
    rating: 'ADVANCED',
    duration: 'Consultative'
  },
  {
    id: 'linkedin-post',
    title: 'Content to LinkedIn Post',
    description: 'Analyzes content on a webpage, then generates a LinkedIn Post that can be copied to your clipboard.',
    category: 'Social Media',
    imageUrl: 'https://picsum.photos/seed/linkedin-post/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/copy-of-content--linkedin-post-d82c5656/remix',
    tags: ['Social', 'LinkedIn', 'Content'],
    match: 88,
    rating: 'EASY',
    duration: 'Fast'
  },
  {
    id: 'social-ideas',
    title: 'Social Media Ideas',
    description: 'Generate creative and engaging social media post ideas tailored to your brand, audience, and goals.',
    category: 'Social Media',
    imageUrl: 'https://picsum.photos/seed/social-ideas/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/social-media-post-ideas-generator-84f8dac1/remix',
    tags: ['Ideation', 'Marketing', 'Social'],
    match: 89,
    rating: 'INTERMEDIATE',
    duration: 'Brainstorming'
  },
  {
    id: 'email-tone',
    title: 'Email Tone Analyzer',
    description: 'Analyzes emails to assess tone, professionalism, and potential impact on recipients, providing detailed feedback for improvement.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/email-tone/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/email-tone-analyzer-fa75d665/remix',
    tags: ['Communication', 'EQ', 'Business'],
    match: 90,
    rating: 'INTERMEDIATE',
    duration: 'Review'
  },
  {
    id: 'prof-email',
    title: 'Pro Email Assistant',
    description: 'Transform your email communication with an expert assistant that helps craft professional, effective business emails for any situation.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/prof-email/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/professional-email-assistant-d3ecb0ce/remix',
    tags: ['Writing', 'Business', 'Assist'],
    match: 95,
    rating: 'EASY',
    duration: 'Daily'
  },
  {
    id: 'tldr',
    title: 'TLDR Generator',
    description: 'Transform any text into clear, concise summaries that capture the essential information while maintaining context and key details.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/tldr/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/1-tldr--engel--bootcamp-02b43a52/remix',
    tags: ['Summary', 'Speed', 'Reading'],
    match: 98,
    rating: 'EASY',
    duration: 'Instant'
  },
  {
    id: 'email-thread',
    title: 'Thread Summarizer',
    description: 'Transform lengthy email threads into clear, actionable summaries that highlight key points, decisions, and next steps.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/email-thread/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/2-email-thread-summarizer--engel--bootcamp-e9058cc6/remix',
    tags: ['Email', 'Corporate', 'Summary'],
    match: 91,
    rating: 'INTERMEDIATE',
    duration: 'Fast'
  },
  {
    id: 'blog-gen',
    title: 'Blog Post Generator',
    description: 'Transform your ideas into polished, engaging blog posts with AI-powered content generation.',
    category: 'Content',
    imageUrl: 'https://picsum.photos/seed/blog-gen/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/3-basic-blog-post-generator--engel--bootcamp-d1abe508/remix',
    tags: ['Writing', 'Blogging', 'Creativity'],
    match: 89,
    rating: 'EASY',
    duration: 'Fast'
  },
  {
    id: 'dynamic-content',
    title: 'Dynamic Content Gen',
    description: 'A versatile content generator that creates engaging, SEO-optimized web content based on your input and preferences.',
    category: 'Content',
    imageUrl: 'https://picsum.photos/seed/dynamic-content/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/4-dynamic-content-generator--engel--bootcamp-ed5c4a93/remix',
    tags: ['Web', 'SEO', 'Versatile'],
    match: 90,
    rating: 'INTERMEDIATE',
    duration: 'Flexible'
  },
  {
    id: 'youtube-sum',
    title: 'YouTube Summarizer',
    description: 'Get concise, accurate summaries of any YouTube video, including key points, timestamps, and takeaways.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/youtube-sum/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/5-youtube-summarizer--engel--bootcamp-890dacca/remix',
    tags: ['Video', 'Learning', 'Summary'],
    match: 97,
    rating: 'EASY',
    duration: 'Instant'
  },
  {
    id: 'faq-gen',
    title: 'FAQ Generator',
    description: 'Automatically generates comprehensive, relevant FAQs for your website\'s home page based on your content and target audience.',
    category: 'Content',
    imageUrl: 'https://picsum.photos/seed/faq-gen/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/6-home-page-faq-generator--engel--bootcamp-790f37cf/remix',
    tags: ['Support', 'Website', 'Docs'],
    match: 88,
    rating: 'EASY',
    duration: 'Fast'
  },
  {
    id: 'b2b-email',
    title: 'B2B Email Pro',
    description: 'Creates highly personalized cold outreach emails for B2B software sales, tailored to specific industries and company profiles.',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/b2b-email/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/7-personalized-cold-outreach-email-generator--engel--bootcamp-bbbd6b73/remix',
    tags: ['Sales', 'Cold Email', 'Growth'],
    match: 94,
    rating: 'ADVANCED',
    duration: 'Outreach'
  },
  {
    id: 'ask-docs',
    title: 'Ask the Docs',
    description: 'A specialized chat assistant that helps you explore and understand documentation, making complex technical content more accessible.',
    category: 'Development',
    imageUrl: 'https://picsum.photos/seed/ask-docs/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/8--ask-the-docs-chat-bot--engel--bootcamp-a802ae91/remix',
    tags: ['Technical', 'Manuals', 'Chat'],
    match: 93,
    rating: 'INTERMEDIATE',
    duration: 'Interactive'
  },
  {
    id: 'people-extract',
    title: 'People Extractor',
    description: 'Automatically identifies and extracts names of people mentioned in web content, organizing them into a structured database.',
    category: 'Data',
    imageUrl: 'https://picsum.photos/seed/people-extract/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/9--extract-people-mentioned-in-webpage--send-to-db--engel--bootcamp-54c0da92/remix',
    tags: ['Scraping', 'Database', 'CRM'],
    match: 87,
    rating: 'ADVANCED',
    duration: 'Automation'
  },
  {
    id: 'prof-content',
    title: 'Pro Content Creator',
    description: 'Transform your ideas into engaging LinkedIn posts optimized for maximum reach and engagement.',
    category: 'Social Media',
    imageUrl: 'https://picsum.photos/seed/prof-content/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/10--linkedin-post-generator--engel--bootcamp-9a943c5b/remix',
    tags: ['LinkedIn', 'Personal Brand', 'Social'],
    match: 91,
    rating: 'EASY',
    duration: 'Daily'
  },
  {
    id: 'job-radar',
    title: 'Job Radar',
    description: 'Automatically monitors job websites for new, modified, and removed listings, delivering detailed change reports.',
    category: 'Career',
    imageUrl: 'https://picsum.photos/seed/job-radar/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/11--monitor-website-changes--engel--bootcamp-8705e774/remix',
    tags: ['Job Hunt', 'Monitoring', 'Alerts'],
    match: 96,
    rating: 'ADVANCED',
    duration: '24/7'
  },
  {
    id: 'slack-summary',
    title: 'Slack Weekly Summary',
    description: 'Transform your Slack channel discussions into organized, actionable weekly summaries that highlight key topics.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/slack-summary/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/13--slack-channel-weekly-summary--engel--bootcamp-12ed781d/remix',
    tags: ['Teams', 'Communication', 'Agile'],
    match: 92,
    rating: 'INTERMEDIATE',
    duration: 'Weekly'
  },
  {
    id: 'daily-news',
    title: 'Daily News Digest',
    description: 'Transforms the day\'s most important news into concise, professionally formatted email digests customized to your interests.',
    category: 'Productivity',
    imageUrl: 'https://picsum.photos/seed/daily-news/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/14--generate-and-send-a-daily-news-digest-via-email--engel--bootcamp-bc01454e/remix',
    tags: ['News', 'Briefing', 'Smart'],
    match: 95,
    rating: 'EASY',
    duration: 'Daily'
  },
  {
    id: 'research-report',
    title: 'Research Report Gen',
    description: 'Generate a detailed, long-form written report about a provided topic using research that is backed up by verified sources.',
    category: 'Research',
    imageUrl: 'https://picsum.photos/seed/research-report/800/450',
    externalUrl: 'https://app.mindstudio.ai/agents/15--research-report-generator--engel--bootcamp-c6745b2f/remix',
    tags: ['Academic', 'Deep Dive', 'Writing'],
    match: 98,
    rating: 'ADVANCED',
    duration: 'Comprehensive'
  }
];

export const CATEGORIES = [
  "Trending Now",
  "Business",
  "Productivity",
  "Marketing",
  "Career",
  "Legal",
  "Creative",
  "Content",
  "Social Media",
  "Finance"
];